name: Deploy to Production
description: |
  This workflow checks out the latest tag from the repository and deploys it to production.
  It is triggered by pushing a new tag that follows semantic versioning (e.g., v1.0.0).

on:
  push:
    tags:
      - 'v*'  # Trigger only when tags like v1.0.0, v2.1 are pushed

jobs:
  checkout-latest-tag:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all tags and history

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Checkout latest tag
        run: |
          git checkout ${{ steps.get_tag.outputs.tag }}

      - name: Confirm current HEAD
        run: git log -1 --oneline
